#pragma kernel CSMain
#include "Util.compute"

RWStructuredBuffer<float> chunk;
float3 chunkPosition;

float sphere(uint3 id, float3 chunkPosition)
{
    float3 pt = id + chunkPosition;
    float height = sin(pt.x);
    if (pt.y < height)
    {
        return 1.0;
    }
    return -1.0;
}

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint index = indexFromCoords(id);
    float value = sphere(id, chunkPosition);
    chunk[index] = value;
}
